project_id = "lwseavuepbcgqthnwpjb"

[functions.send-admin-invite]
verify_jwt = true

[functions.generate-receipt]
verify_jwt = true

[functions.process-scheduled-messages]
verify_jwt = false

[functions.send-communication]
verify_jwt = true